from .skill_applications import *
from .skill_arithmetic import *
from .skill_schedule import *
from .skill_search import *
from .skill_speech import *
from .skill_spotify import *
from .skill_time import *
from .skill_window import *
from .skill_telegram import *
from .skill_discord import *
